### ISSUE TITLE
jQuery 2.2

### ISSUE THREAD

**Issue by Ramoonus** [Ramoonus/jQuery-Updater#82]
Include jQuery 2.2 in dev build

**Comment by gesutech** [comment]
Greetings. The slider included in the theme of our WordPress site is now malfunctioning with the latest version of jQuery Updater 2.2. The slides no longer appear on our web page after having installed updates to the plugin. Only the thumbnails appear.  Deactivating and reactivating the jQuery 2.2 plugin did not resolve anything. Nor did deleting it and reinstalling it.
The following is the URL to our site so that you may try to view what is happening:
http://gesuschool.udmercy.edu/
Do you have suggestions on what else we may try? Everything was working well prior to updating the plugin.

**Comment by gesutech** [comment]
We also tried deleting and restoring the slides to no avail.

**Comment by Ramoonus** [comment]
@gesutech if deactivation and doesn`t help there is clearly something wrong

**Comment by gesutech** [comment]
Thank you so much! Reloading the .zip file you provided worked! This has been a blessing to our school. God bless you!
